// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pingtunnel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyMsg_TYPE int32

const (
	MyMsg_DATA  MyMsg_TYPE = 0
	MyMsg_PING  MyMsg_TYPE = 1
	MyMsg_KICK  MyMsg_TYPE = 2
	MyMsg_CATCH MyMsg_TYPE = 3
	MyMsg_MAGIC MyMsg_TYPE = 57005
)

var MyMsg_TYPE_name = map[int32]string{
	0:     "DATA",
	1:     "PING",
	2:     "KICK",
	3:     "CATCH",
	57005: "MAGIC",
}

var MyMsg_TYPE_value = map[string]int32{
	"DATA":  0,
	"PING":  1,
	"KICK":  2,
	"CATCH": 3,
	"MAGIC": 57005,
}

func (x MyMsg_TYPE) String() string {
	return proto.EnumName(MyMsg_TYPE_name, int32(x))
}

func (MyMsg_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0, 0}
}

type MyMsg struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Rproto               int32    `protobuf:"zigzag32,5,opt,name=rproto,proto3" json:"rproto,omitempty"`
	Magic                int32    `protobuf:"zigzag32,6,opt,name=magic,proto3" json:"magic,omitempty"`
	Key                  int32    `protobuf:"zigzag32,7,opt,name=key,proto3" json:"key,omitempty"`
	Timeout              int32    `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Tcpmode              int32    `protobuf:"varint,9,opt,name=tcpmode,proto3" json:"tcpmode,omitempty"`
	TcpmodeBuffersize    int32    `protobuf:"varint,10,opt,name=tcpmode_buffersize,json=tcpmodeBuffersize,proto3" json:"tcpmode_buffersize,omitempty"`
	TcpmodeMaxwin        int32    `protobuf:"varint,11,opt,name=tcpmode_maxwin,json=tcpmodeMaxwin,proto3" json:"tcpmode_maxwin,omitempty"`
	TcpmodeResendTimems  int32    `protobuf:"varint,12,opt,name=tcpmode_resend_timems,json=tcpmodeResendTimems,proto3" json:"tcpmode_resend_timems,omitempty"`
	TcpmodeCompress      int32    `protobuf:"varint,13,opt,name=tcpmode_compress,json=tcpmodeCompress,proto3" json:"tcpmode_compress,omitempty"`
	TcpmodeStat          int32    `protobuf:"varint,14,opt,name=tcpmode_stat,json=tcpmodeStat,proto3" json:"tcpmode_stat,omitempty"`
	ServerSend           int32    `protobuf:"varint,15,opt,name=server_send,json=serverSend,proto3" json:"server_send,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyMsg) Reset()         { *m = MyMsg{} }
func (m *MyMsg) String() string { return proto.CompactTextString(m) }
func (*MyMsg) ProtoMessage()    {}
func (*MyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *MyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMsg.Unmarshal(m, b)
}
func (m *MyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMsg.Marshal(b, m, deterministic)
}
func (m *MyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMsg.Merge(m, src)
}
func (m *MyMsg) XXX_Size() int {
	return xxx_messageInfo_MyMsg.Size(m)
}
func (m *MyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MyMsg proto.InternalMessageInfo

func (m *MyMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MyMsg) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MyMsg) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *MyMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MyMsg) GetRproto() int32 {
	if m != nil {
		return m.Rproto
	}
	return 0
}

func (m *MyMsg) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *MyMsg) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *MyMsg) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *MyMsg) GetTcpmode() int32 {
	if m != nil {
		return m.Tcpmode
	}
	return 0
}

func (m *MyMsg) GetTcpmodeBuffersize() int32 {
	if m != nil {
		return m.TcpmodeBuffersize
	}
	return 0
}

func (m *MyMsg) GetTcpmodeMaxwin() int32 {
	if m != nil {
		return m.TcpmodeMaxwin
	}
	return 0
}

func (m *MyMsg) GetTcpmodeResendTimems() int32 {
	if m != nil {
		return m.TcpmodeResendTimems
	}
	return 0
}

func (m *MyMsg) GetTcpmodeCompress() int32 {
	if m != nil {
		return m.TcpmodeCompress
	}
	return 0
}

func (m *MyMsg) GetTcpmodeStat() int32 {
	if m != nil {
		return m.TcpmodeStat
	}
	return 0
}

func (m *MyMsg) GetServerSend() int32 {
	if m != nil {
		return m.ServerSend
	}
	return 0
}

func init() {
	proto.RegisterEnum("MyMsg_TYPE", MyMsg_TYPE_name, MyMsg_TYPE_value)
	proto.RegisterType((*MyMsg)(nil), "MyMsg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0xf1, 0x2d, 0xad, 0x8f, 0xdd, 0xd4, 0x3d, 0x5c, 0x74, 0x76, 0x98, 0x4a, 0x48, 0x66,
	0x01, 0x0b, 0xd8, 0xb2, 0x71, 0x0d, 0x2a, 0x51, 0x65, 0x54, 0x39, 0xde, 0xc0, 0x26, 0x72, 0xe2,
	0x89, 0x65, 0x81, 0x2f, 0x9a, 0x99, 0x00, 0x61, 0xc9, 0xfb, 0xf0, 0x08, 0xbc, 0x1b, 0xf2, 0xc9,
	0xb8, 0xbb, 0xff, 0xff, 0xfe, 0xcf, 0x9a, 0x23, 0x19, 0xfc, 0x4e, 0x35, 0x6f, 0x46, 0x39, 0xe8,
	0xe1, 0xfa, 0x8f, 0x0b, 0x5e, 0x7e, 0xcc, 0x55, 0x83, 0x4b, 0xb0, 0xdb, 0x9a, 0xac, 0xd8, 0x4a,
	0xfc, 0xc2, 0x6e, 0x6b, 0x44, 0x70, 0xf5, 0x71, 0x14, 0x64, 0xc7, 0x56, 0xe2, 0x15, 0x9c, 0xf1,
	0x19, 0x2c, 0x74, 0x25, 0x1b, 0xa1, 0xc9, 0x61, 0xcf, 0xb4, 0xc9, 0xad, 0x2b, 0x5d, 0x91, 0x1b,
	0x5b, 0x49, 0x58, 0x70, 0x9e, 0x5c, 0xc9, 0x6f, 0x90, 0x17, 0x5b, 0xc9, 0x55, 0x61, 0x1a, 0x3e,
	0x01, 0xaf, 0xab, 0x9a, 0x76, 0x47, 0x0b, 0xc6, 0xa7, 0x82, 0x11, 0x38, 0xdf, 0xc4, 0x91, 0xce,
	0x98, 0x4d, 0x11, 0x09, 0xce, 0x74, 0xdb, 0x89, 0xe1, 0xa0, 0xe9, 0x9c, 0x4f, 0x98, 0x2b, 0x2f,
	0xbb, 0xb1, 0x1b, 0x6a, 0x41, 0xbe, 0x59, 0x4e, 0x15, 0x5f, 0x03, 0x9a, 0xb8, 0xd9, 0x1e, 0xf6,
	0x7b, 0x21, 0x55, 0xfb, 0x5b, 0x10, 0xb0, 0x74, 0x65, 0x96, 0x9b, 0x87, 0x01, 0x5f, 0xc2, 0x72,
	0xd6, 0xbb, 0xea, 0xd7, 0xcf, 0xb6, 0xa7, 0x80, 0xd5, 0x0b, 0x43, 0x73, 0x86, 0xf8, 0x16, 0x9e,
	0xce, 0x9a, 0x14, 0x4a, 0xf4, 0xf5, 0x66, 0xba, 0xa4, 0x53, 0x14, 0xb2, 0xfd, 0xd8, 0x8c, 0x05,
	0x6f, 0x25, 0x4f, 0xf8, 0x0a, 0xa2, 0xf9, 0x9b, 0xdd, 0xd0, 0x8d, 0x52, 0x28, 0x45, 0x17, 0xac,
	0x5f, 0x1a, 0x9e, 0x19, 0x8c, 0x2f, 0x20, 0x9c, 0x55, 0xa5, 0x2b, 0x4d, 0x4b, 0xd6, 0x02, 0xc3,
	0xd6, 0xba, 0xd2, 0xf8, 0x1c, 0x02, 0x25, 0xe4, 0x0f, 0x21, 0x37, 0xd3, 0x13, 0x74, 0xc9, 0x06,
	0x9c, 0xd0, 0x5a, 0xf4, 0xf5, 0xf5, 0x7b, 0x70, 0xcb, 0x2f, 0xf7, 0x1f, 0xf1, 0x1c, 0xdc, 0x0f,
	0x69, 0x99, 0x46, 0x8f, 0xa6, 0x74, 0xbf, 0xfa, 0x7c, 0x1b, 0x59, 0x53, 0xba, 0x5b, 0x65, 0x77,
	0x91, 0x8d, 0x3e, 0x78, 0x59, 0x5a, 0x66, 0x9f, 0x22, 0x07, 0x03, 0xf0, 0xf2, 0xf4, 0x76, 0x95,
	0x45, 0x7f, 0xff, 0x39, 0x37, 0xe1, 0x57, 0x18, 0xdb, 0xbe, 0xd1, 0x87, 0xbe, 0x17, 0xdf, 0xb7,
	0x0b, 0xfe, 0x4f, 0xef, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x91, 0xfd, 0x3c, 0x26, 0x02,
	0x00, 0x00,
}
